version: '3.8'

services:
  postgres-db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pg_data_local:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    depends_on:
      - postgres-db

volumes:
  pg_data_local:
